### ISSUE TITLE
about password dataset

### ISSUE THREAD

**Issue by ghost** [wtomin/MIMA-Net#16]
I am a student and I have a Anti-Spoofing project at school. But I felt stuck because of the lack of train data.
Would you please to share me the password of train and dev dataset?
I would be grateful for that <3

**Comment by wtomin** [comment]
The training data of my model are from two datasets: the Aff-wild dataset and the OMG dataset. Both of the two datasets are public datasets so you can ask for access to the datasets authors. I'm  concerned of giving you the data directly because the IP issue. I think it will be better if you send the authors emails.
